# database
spring:
  datasource:
    url: {url}
    username: {username}
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secretKey: ${SECRET_KEY:akshflkdsjfasdlfhkdashfhasfksahadfasdfadsfqwdcazfqwedsafas}
  exp:
    access: ${ACCESS_EXP:1800000}
    refresh: ${REFRESH_EXP:17280000000}
server:
  port: 8080
